const dummyData = [
    {
      masterOId: '123',
      contentLaunchDate: '2023-10-10',
      completionStatus: 'Completed',
      completedInDays: 5,
      challenges: 'Active',
      completionDate: '2023-10-15',
      attempts: 'First Attempt',
      score: 85,
      maxScore: 100,
      timeSpent: '2 hours',
      microskillName: 'Critical Thinking',
      loginStatus: 'Logged In',
      lastLoginDate: '2023-12-01',
    },
    {
      masterOId: '124',
      contentLaunchDate: '2023-10-11',
      completionStatus: 'Pending',
      completedInDays: 8,
      challenges: 'Inactive',
      completionDate: '2023-10-20',
      attempts: 'Second Attempt',
      score: 92,
      maxScore: 100,
      timeSpent: '1.5 hours',
      microskillName: 'Problem Solving',
      loginStatus: 'Logged Out',
      lastLoginDate: '2023-11-25',
    },
    {
      masterOId: '125',
      contentLaunchDate: '2023-10-12',
      completionStatus: 'In Progress',
      completedInDays: 3,
      challenges: 'Active',
      completionDate: '2023-10-16',
      attempts: 'Third Attempt',
      score: 70,
      maxScore: 100,
      timeSpent: '3 hours',
      microskillName: 'Teamwork',
      loginStatus: 'Logged In',
      lastLoginDate: '2023-12-02',
    },
    {
      masterOId: '126',
      contentLaunchDate: '2023-10-13',
      completionStatus: 'Completed',
      completedInDays: 6,
      challenges: 'Active',
      completionDate: '2023-10-18',
      attempts: 'First Attempt',
      score: 95,
      maxScore: 100,
      timeSpent: '2.5 hours',
      microskillName: 'Adaptability',
      loginStatus: 'Logged In',
      lastLoginDate: '2023-12-03',
    },
    {
      masterOId: '127',
      contentLaunchDate: '2023-10-14',
      completionStatus: 'Pending',
      completedInDays: 7,
      challenges: 'Inactive',
      completionDate: '2023-10-21',
      attempts: 'Second Attempt',
      score: 88,
      maxScore: 100,
      timeSpent: '3.5 hours',
      microskillName: 'Leadership',
      loginStatus: 'Logged Out',
      lastLoginDate: '2023-11-28',
    },
  ];
  
  export default dummyData;
  